# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build rackshift image with maven & node

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        check-latest: true
    - name: Build with Maven
      run: |
        sudo docker login --username=${{secrets.DH_USERNAME}} --password=${{ secrets.DH_PWD }}
        cd ./rackshift-web
        npm install
        npm run build
        rm -rf ../rackshift-server/src/main/resources/static
        mkdir -p ../rackshift-server/src/main/resources/static
        cp -r ./dist/* ../rackshift-server/src/main/resources/static
        cd ../
        mvn clean install -DskipTests
        cd ./rackshift-server
        docker build -t rackshift/rackshift:actions .
        docker push rackshift/rackshift:actions